name: athletics_training_app
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  audioplayers: ^6.1.0
  flutter_local_notifications: ^18.0.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive: ^2.2.3
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1

flutter_icons:
    image_path_android: "assets/icons/playstore.png"
    image_path_ios: "assets/icons/playstore.png"
    android: true
    ios: true
    remove_alpha_ios: true

flutter_launcher_icons:
  image_path: "assets/icons/playstore.png"
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21
  remove_alpha_channel_ios: true

  web:
    generate: true
    image_path: "assets/icons/playstore.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

  windows:
    generate: true
    image_path: "assets/icons/playstore.png"
    icon_size: 48 

  macos:
    generate: true
    image_path: "assets/icons/playstore.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/playstore.png
    - assets/sounds/notification.mp3
